### ISSUE TITLE
Jenkins build show up in the VSM GUI only when there is a new pull request

### ISSUE THREAD

**Issue by fewproud** [UrbanCode/velocity-info#15]
I'm using UCV 1.4.2. I used 1.3 before and recently re-installed (not upgrade) v1.4.2. I found the Jenkins build didn't show up in the VSM GUI correctly. It only show the first build after a new pull request. If you built again, this new build would not be listed in the VSM GUI. 

See these:
{ "_id" : ObjectId("5e1a8445496de0365181c8ca"), "id" : "app-build - 64", "tenantId" : ObjectId("5ade13625558f2c6688d15ce"), "name" : "#64", "versionName" : "#64", "status" : "success", "application" : { "name" : "demoapp", "external_id" : "d9a0d57b-1ece-4aa9-9461-9baf7053d267", "externalId" : "d9a0d57b-1ece-4aa9-9461-9baf7053d267", "id" : "d9a0d57b-1ece-4aa9-9461-9baf7053d267" }, "url" : "http://myhost:8080/job/UCV-demos/job/jenkins/job/app-build/64/", "startTime" : 1578796099949, "endTime" : 1578796100704, "requestor" : "admin", "revision" : "981ad7f791eecbd00a91f14514762308e9f73e70", "tenant_id" : "5ade13625558f2c6688d15ce", "startTimeISO" : ISODate("2020-01-12T02:28:19.949Z"), "endTimeISO" : ISODate("2020-01-12T02:28:20.704Z"), "teams" : [ ], "tags" : [ ], "applicationId" : "d9a0d57b-1ece-4aa9-9461-9baf7053d267", "issueIds" : [ ObjectId("5e17de740c6ee0d97ec514b8") ], "commitIds" : [ ObjectId("5e1a8494496de0221f81c8d0") ], "pullRequestIds" : [ ] }
{ "_id" : ObjectId("5e1aad9e496de05b2581c910"), "id" : "app-build - 65", "tenantId" : ObjectId("5ade13625558f2c6688d15ce"), "name" : "#65", "versionName" : "#65", "status" : "success", "application" : { "name" : "demoapp", "external_id" : "d9a0d57b-1ece-4aa9-9461-9baf7053d267", "externalId" : "d9a0d57b-1ece-4aa9-9461-9baf7053d267", "id" : "d9a0d57b-1ece-4aa9-9461-9baf7053d267" }, "url" : "http://myhost:8080/job/UCV-demos/job/jenkins/job/app-build/65/", "startTime" : 1578806685143, "endTime" : 1578806685938, "requestor" : "admin", "revision" : "981ad7f791eecbd00a91f14514762308e9f73e70", "tenant_id" : "5ade13625558f2c6688d15ce", "startTimeISO" : ISODate("2020-01-12T05:24:45.143Z"), "endTimeISO" : ISODate("2020-01-12T05:24:45.938Z"), "teams" : [ ], "tags" : [ ], "applicationId" : "d9a0d57b-1ece-4aa9-9461-9baf7053d267", "issueIds" : [ ], "commitIds" : [ ], "pullRequestIds" : [ ] }

You can see the second build has null issueids, ciommitIds. Is it a defect?

**Comment by daniel-trow** [comment]
I believe the empty arrays make sense, if it was a rebuild without being tied to an issue or commit. The VSM view is geared towards issues, PRs, and commits. From a work item perspective, a build only means something if it's tied to one of these.

However, rebuilds should affect metrics and insights. For instance, subsequent builds should show up in the insights build chart. However, if no new work has been merged, then these builds do not necessarily represent workflow unless we were to specifically design our value stream that way. In this case, from this value stream's perspective, we can keep rebuilding the same code but that doesn't necessarily mean that more work is getting done (the build frequency should go up though). If I understand the issue correctly, I think this makes sense and is not a defect.

**Comment by fewproud** [comment]
> I believe the empty arrays make sense, if it was a rebuild without being tied to an issue or commit. The VSM view is geared towards issues, PRs, and commits. From a work item perspective, a build only means something if it's tied to one of these.
> 
> However, rebuilds should affect metrics and insights. For instance, subsequent builds should show up in the insights build chart. However, if no new work has been merged, then these builds do not necessarily represent workflow unless we were to specifically design our value stream that way. In this case, from this value stream's perspective, we can keep rebuilding the same code but that doesn't necessarily mean that more work is getting done (the build frequency should go up though). If I understand the issue correctly, I think this makes sense and is not a defect.

I think this sounds reasonable. If VSM is designed to behavior like this, it's OK. Thanks for your reply.
