### ISSUE TITLE
How do I use oAuth with Jira?

### ISSUE THREAD

**Issue by contentEditor1** [UrbanCode/velocity-info#2]
I want to use oAuth with Jira but I'm not sure how to set this up.

**Here's what I have**
[https://developer.atlassian.com/server/jira/platform/oauth/](https://developer.atlassian.com/server/jira/platform/oauth/)

![oauth](https://user-images.githubusercontent.com/55764427/66968754-9dfc7d80-f054-11e9-97cf-b7a16269e038.jpg)

**Comment by daniel-trow** [comment]
See https://github.com/UrbanCode/velocity-info/issues/3

For suggested features check [The RFE community](https://www.ibm.com/developerworks/rfe/execute?use_case=searchRFEs&SELECTED_SEARCH_TAB=TAB1&SPECIFY_PRODUCT_TYPE=SPECIFY_PRODUCT_ONLY&BRAND_ID=90&PROD_FAM_ID=675&BRAND_ID_SEARCH=90&PROD_FAM_ID_SEARCH=675&PROD_ID_SEARCH=20136&COMP_ID=416&CREATED_BY=&KEYWORDS=&KW_TYPE=1&START_DATE=&STOP_DATE=&CR_ID=&COMPANY=&GROUP_ID=&rfenumber=id&PAGE=1&ITEMS_PER_PAGE=20&SORT_BY=RESP_ID&SORT_ORDER=ASC&HIDE_DESCRIPTIONS=true&is_javascript_enabled=false)
