### ISSUE TITLE
Mention Kanban Template in Jira section

### ISSUE THREAD

**Issue by kzsh** [UrbanCode/velocity-info#20]
in `2.1 Setting Up Jira`, under the `Jira Board` bullet, the expected list of columns matches the Kanban template which is one of the offered to new projects in Jira.  It might be nice to mention that selecting the Kanban template will produce the desired result.

**Comment by kzsh** [comment]
Seeing the differences between Kanban and what's mentioned in the tutorial, maybe the exact columns aren't really important, though 🤷

**Comment by daniel-trow** [comment]
yea, Kanban is not required, but it's the recommended choice, so should probably be mentioned. Merged!
https://github.com/UrbanCode/velocity-info/commit/08152952ffa2d2a03d00e35aae1f7de5c11a4cf2
