### ISSUE TITLE
New Integration Modal action is "Add" not "Save"

### ISSUE THREAD

**Issue by kzsh** [UrbanCode/velocity-info#21]
Under `2.2 Creating a Jira integration`
In step 8 "Save" should be "Add".

**details**:
Step 8 mentions `After clicking on “Save” the integration should be created and visible on the integrations page.`.

It looks like the UI verb for submitting that form is actually "Add", so we might want to update the text to read `After clicking on “Add” the integration should be created and visible on the integrations page.`

**Comment by daniel-trow** [comment]
Good catch, merged!
https://github.com/UrbanCode/velocity-info/commit/b878f41b981877e658c5750b8e2bb94c818f1d54
