### ISSUE TITLE
Section 3.3 step 5 Github Integration step differing result

### ISSUE THREAD

**Issue by kzsh** [UrbanCode/velocity-info#22]
When I successfully integrate github into the value stream, my stream looks a little different than the screenshot in the tutorial.

### Expected:
![](https://urbancode.github.io/velocity-info/workbooks/github/movingDots/in%20progress.png)

### My result:
![Screen Shot 2020-04-20 at 13 18 35](https://user-images.githubusercontent.com/1041312/79780205-8fe03000-8309-11ea-88ea-6500f5ff673a.png)

Should I have expected UCV to update Jira?  Or would I need to have moved the Jira issue to in-progress manually?

**Comment by daniel-trow** [comment]
UCV does not currently update Jira cards, so yes, you will need to update the card in Jira first, then Velocity will reflect any Jira changes.

I also noticed the square that is "In Progress" in your screenshot. That means there is a PR not linked to a work item.
